### PR TITLE
About/Careers Pages

### PR DESCRIPTION
**Pull request by AlecRust**
Needs some more copy if anyone has some stuff they want to include? Are there more pages we want too?

Also:
- Move "Contact" to new small nav in footer, which includes "Careers"

**About:**
screenshot

**Careers:**
screenshot

### CODE REVIEW

**Comment by adiel** [comment]
This looks excellent. What other content do we need. I was thinking we'd put some actual open roles on here:

* Developer (consider any level?)
* Project/Delivery Director (i.e head PM)
* Project/Delivery Lead (underling PM)
* Designer?
* QA ?

Doesn't mean we have to hire any of these people but shows we mean business and that we would consider it for the right people

**Comment by AlecRust** [comment]
Cool have added a "Current Positions" section and pages:

screenshot

**Comment by adiel** [comment]
screen shot 2017-11-16 at 12 31 41

**Comment by adiel** [comment]
screen shot 2017-11-16 at 12 46 33

**Pull request merged**
